[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "opencaptions"
version = "0.1.0"
description = "OpenCaptions full monorepo package"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "openai-whisper",
]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]
include = [
    "opencaptions*",
    "packages*",
    "scripts*",
    "fixtures*",
    "integrations*"
]