[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "opencaptions"
version = "0.1.0"
description = "OpenCaptions full monorepo package"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "openai-whisper",
]

[project.scripts]
opencaptions = "opencaptions:main"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]
include = [
    "opencaptions*",
]

[tool.setuptools.package-data]
opencaptions = [
    "../package.json",
    "../bun.lockb",
    "../turbo.json",
    "../packages/**/dist/**/*",
    "../packages/**/src/**/*",  
    "../packages/**/*",
    "../scripts/**/*",
    "../fixtures/**/*",
    "../integrations/**/*"
]